api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views2 as views


router = routers.DefaultRouter()
router.register(r'messages', views.MessageViewSet, basename='messages')
router.register(r'chat', views.ChatViewSet, basename='chat')

#router.register(r'users', views.UsersView)
#router.register(r'monitor', views.MonitorView)

app_name = 'api'
urlpatterns = [
	path('', include(router.urls)),
]

chat/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views



app_name = 'chat'
urlpatterns = [
    path(r'', login_required(views.MessengerView.as_view()), name='messenger'),
    path(r'<int:chat_id>', login_required(views.ChatView.as_view()), name='chat'),
    path(r'create_chat', login_required(views.create_chat), name='create_chat'),
    path(r'send', login_required(views.send), name='send'),
    path(r'start_chat/<int:friend_id>', views.start_chat, name='start_chat'),
    path(r'add_friend', login_required(views.add_friend), name='add_friend'),
    path(r'unread_messages/', login_required(views.unread_messages), name='unread_messages'),
    path(r'clear_expired/', login_required(views.clear_expired), name='clear_expired'),
    path(r'add_to_chat', login_required(views.add_to_chat), name='add_to_chat'),
    path(r'delete_friend', login_required(views.delete_friend), name='delete_friend'),
    path(r'confirm_delivery/<int:chat_id>', login_required(views.confirm_delivery), name='confirm_delivery'),
    path(r'confirm_seen/<int:chat_id>', login_required(views.confirm_seen), name='confirm_seen'),
    ]

chatapp/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls'), name='chat'),
    path('api/', include('api.urls'), name='api'),
    path('', include('website.urls'), name='index')
]

chat/models.py
from django.db import models
import datetime


class Chat(models.Model):
	owner = models.ForeignKey('website.Account', on_delete=models.CASCADE, related_name='chat_owner', null=False)
	chat_name = models.CharField(max_length=32, null=True, default='Chat')
	creation_date = models.DateTimeField()
	private = models.BooleanField(default=True)
	users = models.ManyToManyField('website.Account', related_name='users_chats', blank=True)

	def __str__(self):
		return self.chat_name + ' (' + str(self.id) + ')'

class Message(models.Model):
	sender = models.ForeignKey('website.Account', on_delete=models.CASCADE, related_name='message_sender')
	chat = models.ForeignKey('chat.Chat', on_delete=models.CASCADE, related_name='chat_messages', null=True)
	content = models.TextField(max_length=1000, null=True)
	timestamp = models.DateTimeField(blank=True, null=True)
	sent = models.BooleanField(default=False)
	delivered = models.BooleanField(default=False)
	seen = models.BooleanField(default=False)
	destruct_timer = models.IntegerField(null=True)



	@property
	def remaining(self):
		if self.destruct_timer:
			return ((self.timestamp.timestamp() + self.destruct_timer) - datetime.datetime.now().timestamp()).__round__(0)


	def __str__(self):
		return str(self.timestamp) + ' ' + self.sender.user.get_username() + ': ' + str(self.content)

chat/forms.py
from django import forms


class FindUsersForm(forms.Form):
    name = forms.CharField(label='Username', max_length=32,
                           widget=forms.TextInput(attrs={'placeholder': 'Find users/rooms'}))


class CreateChatForm(forms.Form):
    chat_name = forms.CharField(max_length=16, label='Create chat', widget=forms.TextInput(attrs={'placeholder': 'Chat name..'}))
    private = forms.BooleanField(required=False)


class ClearChatForm(forms.Form):
    all_msgs = forms.BooleanField(label='Delete all messages', initial=False,
                                  help_text='If checked, also deletes incoming messages.')


class AddToChat(forms.Form):
    friend = forms.CharField(max_length=32)


    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['friend'].choices = [(friend.id, friend.user.username) for friend in request.user.user_account.friends.all()]

chat/views.py
import datetime
from itertools import chain
import re

from django.shortcuts import render, HttpResponseRedirect, redirect, HttpResponse
from django.http import JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.generic import TemplateView
from django.db.models import Q
from .forms import FindUsersForm, AddToChat, CreateChatForm, ClearChatForm
from .utils import see_users, clear_chat, clear_users_history
from .models import Message, Chat
from website.models import Account


class MessengerView(TemplateView):
    template_name = 'chat/messenger.html'
    find_users_form = FindUsersForm
    create_chat_form = CreateChatForm


    def post(self, request, *args, **kwargs):
        account = equest.user.user_account
        if 'add_friend' in str(request.POST):
            friend = Account.objects.get(id=request.POST['add_friend'])
            if friend not in account.friends.all():
                account.friends.add(friend)
                account.save()
                return HttpResponseRedirect(reverse('chat:chat', args=(friend.id,)))
        return HttpResponseRedirect(reverse('chat:messenger'))

    def get_context_data(self, *args, **kwargs):
        account = self.request.user.user_account
        user_id = account.id
        users_online = see_users()
        friends = [(f.user.username, f.id, f.user in users_online) for f in account.friends.all()]
        friend = None
        chats = None

        owned_chats = Chat.objects.filter(owner=account)
        joined_chats = account.users_chats.all()
        public_chats = Chat.objects.filter(private=False)

        search_results = []
        if 'name' in str(self.request.GET):
            find_form = FindUsersForm(self.request.GET)
            if find_form.is_valid():
                form_data = find_form.cleaned_data
                search_results = User.objects.filter(username__icontains=form_data['name'])
            else:
                print(f'Errors: {find_form.errors}')
        return {'user_id': user_id, 'friend': friend, 'friends': friends, 'chats': chats,
                 'online_users': users_online,
                'create_chat': self.create_chat_form, 'find_friends_form': self.find_users_form,
                'search_results': search_results, 'chat_id': 0, 'owned_chats': owned_chats, 'joined_chats':
                joined_chats, 'public_chats': public_chats}


class ChatView(MessengerView):
    template_name = 'chat/chat.html'

    def get(self, request, *args, **kwargs):
        print('gettin')
        print(kwargs)
        account = self.request.user.user_account
        chat_id = kwargs['chat_id']
        if not Chat.objects.filter(id=chat_id).exists():
            return HttpResponse('Forbidden. Chat does not exist..')
        chat = Chat.objects.get(id=chat_id)
        if chat.private and account not in chat.users.all():
            return HttpResponse('Forbidden. Need invite to join chat.')
        context = self.get_context_data(*args, **kwargs)
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        account = self.request.user.user_account
        #friend = Account.objects.get(id=kwargs['friend_id'])
        if 'clear_history' in str(request.POST):
            print('clearing hist')
            print(kwargs)
            chat_id = kwargs['chat_id']
            if Chat.objects.filter(id=chat_id).exists():
                Message.objects.filter(chat_id=chat_id).delete()
                return HttpResponseRedirect(reverse('chat:chat', args=(chat_id,)))
            #clear_history(account.id, friend.id)


        elif re.search('leave_chat', str(request.POST)):
            print('leavin')
            print(request.POST)
            chat_id = request.POST['drop_from_chat_chat_id']
            if Chat.objects.filter(id=chat_id).exists():
                chat = Chat.objects.get(id=chat_id)

                if account == chat.owner:
                    chat.delete()
                elif account in chat.users.all():
                    Message.objects.create(sender=account, chat=chat, timestamp=datetime.datetime.now(),
                                                       content=f'{account} has left the chat.')

                    chat.users.remove(account)

                return HttpResponseRedirect(reverse('chat:messenger'))

        elif re.search('kick_from_chat', str(request.POST)):
            print('kickin')
            print(request.POST)
            chat_id = request.POST['drop_from_chat_chat_id']
            friend_id = request.POST['kick_from_chat']

            if not Account.objects.filter(id=friend_id).exists() or not Chat.objects.filter(id=chat_id).exists():
                return HttpResponse('No such chat or user.')
            friend = Account.objects.get(id=friend_id)
            chat = Chat.objects.get(id=chat_id)

            if chat.owner != account:
                return HttpResponse('Unauthorized. Only chat owner can kick users.')

            if friend == request.user.user_account:
                print('deletin')
                chat.delete()
                return HttpResponseRedirect(reverse('chat:messenger'))
            if friend in chat.users.all():
                chat.users.remove(friend)
                chat.save()
                return HttpResponseRedirect(reverse('chat:chat', args=(chat_id,)))

    def get_context_data(self, *args, **kwargs):
        account = self.request.user.user_account
        context = super().get_context_data(**kwargs)
        print(kwargs)
        chat_id = kwargs['chat_id']

        if 'chat_id' in kwargs.keys():
            chat, created = Chat.objects.get_or_create(id=kwargs['chat_id'], defaults={'owner': account,
                                                                                       'creation_date': datetime.datetime.now()})
            print(chat.users)
            print(chat.users.all())
            if account not in chat.users.all():
                chat.users.add(account)



        context['chat'] = chat
        context['chat_id'] = chat.id

        #context['unread_msgs'] = self.get_unread_msgs()

        context['messages'] = Message.objects.filter(chat=chat)
        context['account'] = account
        context['friend'] = friend if 'friend_id' in kwargs.keys() else None
        context['add_to_chat_form'] = AddToChat
        return context







def unread_messages(request):
    print('get unread')
    res = []
    acc = request.user.user_account
    for chat in acc.users_chats.all():
        msgs = Message.objects.filter(chat=chat).filter(seen=False).filter(~Q(sender=acc)).values()
        for msg in msgs:
            msg['sender'] = Account.objects.get(id=msg['sender_id']).user.username
            res.append(msg)
    print(f' unread: {res}')
    return JsonResponse(res, safe=False)

def clear_expired(request):
    print('clearings')
    for msg in Message.objects.all():
        if msg.destruct_timer and (msg.timestamp.timestamp() + msg.destruct_timer) - datetime.datetime.now().timestamp() <= 0:
            msg.delete()
    return HttpResponse('deleted')


def send(request):
    if request.method == 'POST':
        print(f'send {request.POST}')
        chat_id = request.POST['chat']
        account = request.user.user_account
        print(account)
        date = datetime.datetime.now(tz=datetime.timezone(datetime.timedelta(hours=1)))
        destruct_timer = request.POST['destruct_timer']

        # expiry_date = datetime.datetime.fromtimestamp(datetime.datetime.now().timestamp() + int(destruct_timer)*1000)

        Message.objects.create(sender=account, chat_id=chat_id, content=request.POST['content'],
                               timestamp=date, destruct_timer=destruct_timer, sent=True)

        return HttpResponseRedirect(reverse('chat:chat', args=(chat_id,)))


def confirm_seen(request, chat_id):
    if request.method == 'POST':
        print(f'confirm seen: post {request.POST}')

        Message.objects.filter(chat_id=chat_id).filter(~Q(sender=request.user.user_account)).update(
            seen=True)  # .order_by('-timestamp')
    return HttpResponse('Messages have been seen.')


def confirm_delivery(request, chat_id):
    if request.method == 'POST':
        print(f'confirm deliv: req post {request.POST}')
        account = request.user.user_account
        Message.objects.filter(chat_id=chat_id).filter(~Q(sender=account)).update(
            delivered=True)  # .order_by('-timestamp')
        return HttpResponse('Delivery confirmed.')


def start_chat(request, friend_id):
    acc = request.user.user_account
    friend_acc = Account.objects.get(id=friend_id)
    for chat in acc.users_chats.all():
        if friend_acc in chat.users.all() and chat.users.all().count() < 3:
            print('gogogog')
            return HttpResponseRedirect(reverse('chat:chat', args=(chat.id,)))
    chat = Chat.objects.create(owner=acc, creation_date=datetime.datetime.now())
    Message.objects.create(sender=acc, chat=chat, timestamp=datetime.datetime.now(),
                           content=f'Chat created by {acc}')
    chat.users.add(acc)
    chat.users.add(friend_acc)
    return HttpResponseRedirect(reverse('chat:chat', args=(chat.id,)))










def delete_friend(request):
    account = request.user.user_account
    if request.method == "POST" and 'del_friend_btn' in str(request.POST):
        friend = Account.objects.get(id=request.POST['del_friend_btn'])
        if friend in account.friends.all():
            account.friends.remove(friend)
            account.save()
        return HttpResponseRedirect(reverse('chat:messenger'))


def add_to_chat(request):
    if request.method == 'POST':
        print(request.POST)
        user = request.user.user_account
        friend_id = request.POST['add_to_chat_btn']
        chat_id = request.POST['chat_id']

chat/templates/chat/_add_friend.html
<form id="find_friends_form" method="get" action="#">
    <h3 id="friends_search_label">
        Find users
    </h3>
    {{ find_users.as_p }}

    <button id="find_friends_button" type="submit" name="find_users">
        Search
    </button>
</form>

<h3 id="search_results_label">
    Search results
</h3>
<ul id="friends_search_results" class="w3-ul">
    {% for user in search_results %}
        <li id="{{ user.id }}">
            <div class="search_result_name">

                    {{ user.username }}

            </div>
            <div class="search_result_buttons">

                <form id="add_friend_form{{ user.id }}" method="post" action="#">
                    {% csrf_token %}
                    <input type="hidden" name="chat_id" value="{{ chat_id }}">
                    <button id="add_friend{{ user.id }}" type="submit" name="add_friend" value="{{ user.id }}" class="add_button">
                        Add
                    </button>
                </form>
            </div>
        </li>
    {% endfor %}
</ul>

chat/templates/chat/_chat_list.html
    <div id="chat_table_div">
        <h2>
            Owned chats
        </h2>
        {% include 'chat/_chat_table.html' with chats=owned_chats %}
        <h2>
            Joined chats
        </h2>
        {% include 'chat/_chat_table.html' with chats=joined_chats %}

        <h2>
            Pubilc chats
        </h2>
        {% include 'chat/_chat_table.html' with chats=public_chats %}
    </div>

chat/templates/chat/_chat_table.html
        <table id="chat_table">
            <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Status
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for chat in chats %}
                <tr>
                    <td>
                        <a href="/chat/{{ chat.id }}"> {{ chat.chat_name }} ({{ chat.id }})  </a>
                    </td>

                    <td>
                        {% if chat.private %}
                            Private
                        {% else %}
                            Public
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

chat/templates/chat/_chat_top.html
 <div id="chat_top_div">

        <h3 id="chat_header">
           Chat: {{ chat.chat_name }}
        </h3>

        <ul id="chat_members">
            {% for user in chat.users.all %}
            <li>
                <ul>
                    <li>
                        {{ user }}
                    </li>
                    <li>
                        <form id="drop_from_chat_form_{{ user.id }}" method="POST" action="#">
                            {% csrf_token %}
                            <input type="hidden" name="drop_from_chat_chat_id" value="{{ chat_id }}">

                                {% if user == request.user.user_account %}
                                    <button id="leave_chat_btn" name="leave_chat_btn" value="leave"">
                                        Leave
                                     </button>
                                {% else %}
                                    <button id="kick_from_chat_{{ user.id }}" name="kick_from_chat" value="{{ user.id }}">
                                            Kick
                                        {% endif %}
                                    </button>
                        </form>
                    </li>
                </ul>

            </li>
            {% endfor %}
        </ul>
        <form id="clear_chat_form" method="post" action="#">
            {% csrf_token %}
            <button id="clear_chat_history" type="submit" name="clear_history" value="{{ chat_id }}">
                Clear
            </button>
        </form>

        <div id="destruct_div">
             <button id="rename_button" type="submit" name="rename_chat_btn">
                Rename
            </button>
            <label
             <input type="checkbox" id="private_checkbox"  name="private_checkbox">


            <h4 id="destruct_text">
                Destruct timer
            </h4>

            <select id="destruct_select">
                <option id="des_option_off" name="des_option_off" value="0">
                    Off
                </option>
                <option id="des_option_5s" name="des_option_5s" value="5">
                    5s
                </option>
                <option id="des_option_1m" name="des_option_1m" value="60">
                    1m
                </option>
                <option id="des_option_5m" name="des_option_5m" value="300">
                    5m
                </option>
                <option id="des_option_30m" name="des_option_30m" value="1800">
                    30m
                </option>
                <option id="des_option_1h" name="des_option_1h" value="3600">
                    1h
                </option>
                <option id="des_option_2h" name="des_option_2h" value="7200">
                    2h
                </option>
                <option id="des_option_24h" name="des_option_24h" value="86400">
                    24h
                </option>
            </select>

        </div>


    </div>

chat/templates/chat/_chat_window.html
    <div id="chat_textarea_div">
        <textarea id="chat_textarea" disabled="disabled">
        </textarea>
    </div>

chat/templates/chat/_friend_list.html
<div id="friend_list">
    <h2>
        Friends
    </h2>


<table id="friend_list_table">

    <tbody>
            {% for friend in friends %}
                <tr>
                    <td>
                        <h5>
                            <a href="/chat/start_chat/{{ friend.1 }}"> {{ friend.0 }} </a>
                        </h5>
                    </td>
                    <td>
                        {% if friend.2 %}
                            <img src="{% static 'img/green-dot.png' %}" alt="x" width="18px" height="18px">
                        {% else %}
                            <img src="{% static 'img/red-dot.png' %}" alt="x" width="18px" height="18px">
                        {% endif %}

                    </td>
                    <td>

                        <form id="add_to_chat_{{ friend.1 }}" method="post" action="/chat/add_to_chat">
                            {% csrf_token %}
                            <input type="hidden" name="chat_id" value="{{ chat.id }}">
                            <button name="add_to_chat_btn" value="{{ friend.1 }}" type="submit">
                                Invite
                            </button>
                        </form>

                    </td>
                    <td>
                    <td>
                        <form id="del_friend_form_{{ friend.1 }}" method="post" action="/chat/delete_friend">
                            {% csrf_token %}
                            <button name="del_friend_btn" value="{{ friend.1 }}" type="submit">
                                X
                            </button>

                        </form>
                    </td>
                </tr>
            {% endfor %}


    </tbody>
</table>


</div>

<div id="find_friends">
    <h3 id="find_friends_header">
        Find friends
    </h3>
    <form id="find_friends_form" method="get" action="">
        {% csrf_token %}
        {{ find_friends_form.as_p }}
        <button type="submit" id="find_friends_btn">
            Search
        </button>
    </form>
    {% if search_results %}
    <table id="search_results_table">
        <tbody>
            {% for result in search_results %}

                <tr>
                    <td>
                        {{ result.username }}
                    </td>
                    <td>
                        <form id="add_friend_form_{{ result.id }}" action="{% url 'chat:add_friend' %}" method="post">
                            {% csrf_token %}
                            <button name="add_friend" value="{{ result.id }}" type="submit">
                                Add friend
                            </button>

                        </form>
                    </td>
                </tr>

            {% endfor %}

        </tbody>
    </table>
    {% endif %}
</div>

chat/templates/chat/_message_form.html
<div id="msg_div">
    <form id="msg_form" method="post" action="">
        {% csrf_token %}
        <input id="friend_id" type="hidden" name="friend_id" value="{{ friend.id }}">
        <button id="clear_msg" type="reset"> Clear </button>
        <input id="msg_text" type="text" name="msg_text">
        <button id="msg_button" type="submit" form="msg_form"> Send </button>
        <input id="destr_timer" type="hidden" value="{{ destruct_select.value }}" name="destruct_timer">
    </form>
</div>

chat/templates/chat/chat.html
{% extends 'chat/messenger.html' %}

{% block content %}
<div id="chat_div">
    <div id="friends_div">
        {% include 'chat/_friend_list.html' %}
    </div>

    <div id="chat_window">
        {% include 'chat/_chat_top.html' %}
        {% include 'chat/_chat_window.html' %}
        {% include 'chat/_message_form.html' %}
    </div>

    <div id="rooms_div">

        {% include 'chat/_chat_list.html' %}
    </div>

</div>
{% endblock %}


{% block js %}

    <script type="text/javascript">
    var user_id = '{{ user_id }}';
    var friend_id = '{{ friend.id }}';
    var chat_id = '{{ chat.id }}';
    var unread_msgs = '{{ unread_msgs }}';
    </script>
    <script src="{% static 'js/chat.js' %}"></script>


{% endblock %}

chat/templates/chat/messenger.html
{% extends 'website/base.html' %}

{% block content %}
<div id="chat_div">
    <div id="friends_div">
        {% include 'chat/_friend_list.html' %}
    </div>

    <div id="chat_window">

    </div>

    <div id="rooms_div">

        {% include 'chat/_chat_list.html' %}
    </div>

</div>
{% endblock %}


{% block js %}

    <script src="{% static 'js/chat.js' %}"></script>


{% endblock %}

chat/templates/chat/room.html
{% extends 'chat/chat.html' %}


{% block js %}

    <script type="text/javascript">
    var room_id = '{{ room.id }}';
    </script>
    <script src="{% static 'js/chat.js' %}"></script>


{% endblock %}